### ISSUE TITLE
New AAXClean

### ISSUE THREAD

**Issue by Mbucari** [VarSell/iAmDeaf#1]
Not an issue, but I wanted to tell you that I've mad a lot of changes to AAXClean recently.  There are a lot of speed and memory improvements, so you may want to check it out.

**Comment by VarSell** [comment]
@Mbucari Thanks for letting me know. Updated the package from what I was using before, and am suprised that you managed to optimize it even further. Just tested several large files and the decryption/writing slid down from 8~ to an impressive 3~ sec. (Thanks!)

May I ask if it's possible to change one thing?
With AAXClean.Codecs the DLLs (**ffmpegaac_x64.dll**, **libmp3lame.64.dll**) are no longer extracted to `AppDomain.CurrentDomain.BaseDirectory`, like the LAME DLLs in the previous version were.
They are now extracted to (in my case) the current Directory in which the Shell/Terminal is running in. This leaves behind unwanted (to the user) files over the place (usually the default **C:\Users\<User**) whenever decrypting a file, especially if the program is started via double-click on an associated file.
It would be easy enough to change Current Directory to BaseDirectory for the DLLs to be extracted to a "hidden" dir from the user if not. Thanks either way for the update 👍

**Comment by Mbucari** [comment]
Done. See version 0.2.1

**Comment by VarSell** [comment]
> Done. See version 0.2.1

Works seamlessly, thank you 😺

**Comment by Mbucari** [comment]
Hey there. I just wanted to let you know I made some significant changes to AAXClean.

- Lower CPU utilization with same or better performance.
- Better error reporting. Previous versions swallowed exceptions. The new version will throw them without locking up (that was a problem).
- Better DLL management. Now DLLs are added to your project from the nuget package instead of being extracted from resources.
- New async task paradigm. See the [AAXClean readme](https://github.com/Mbucari/AAXClean#readme) for an explanation and examples.
- AAXClean.Codecs has a new `ConvertToMp4aAsync` method for transcoding AAC audio. Currently in beta, and only single file support.
- AAXClean.Codecs has been croxx-platform for a while. I don't know if that's useful toy you, but there it is.

**Comment by VarSell** [comment]
Thanks for letting me know 👍
Will update the library in the coming days, goodness knows this code needs a rewrite as well aha. Thanks again.
