### ISSUE TITLE
Unable to change output to MP3 or limit other output files.

### ISSUE THREAD

**Issue by tatteredMind** [VarSell/iAmDeaf#2]
Extracted iAmDeaf.7z 2.0.2 to folder
Environment Variable iAmDeaf set to above location of iAmDeaf.exe
ProfileSetup.cmd not creating profile in \appdata\Local\Audible.
.aax set to "Open With" iAmDeaf by default. Double clicking .aax opens iAmDeaf cmd window.
src\data\KeyHistory\log looks to contain hash and decryption bytes

Some .aax files result in error of "MetaBox has xx children of type Mpeg4Lib.Boxes.AppleListBox. Call GetChildren instead." Others do not.

Output folders contains .cue, .jpg, .m4b, .nfo. Settings in src/config.json set to "false" or "mp3" does not change output folder.

**Comment by VarSell** [comment]
Hi, may I ask if for the .aax files that resulted in an error, you used any software to download them, or if it was downloaded normally via the browser?

Not quite sure why ProfileSetup.cmd doesn't create the profile, it should only exit if a profile already exists. All it does is simply run `src\tools\audible quickstart` via cmd. Try running it manually and see what is says.

In the /config.json **"DEFAULT"** must be set to **"true"** if you want to it to use the following settings. If the nfo, cover and cue are still being created, is it possible you set them to **"false"** under **"AAXC"**, and not ["Files"](https://pastebin.com/gf0Q1kcP)?

**Comment by tatteredMind** [comment]
I don't remember how I downloaded the aax files from before, but I just redownloaded from my Audible library and ran whole files (note sure if using the parts was the problem). I set the config.json DEFAULT set to "true" and it outputs a single MP3 (or splits) and jpg while not producing cue and nfo like I set. Point of notice, the iAmDeaf.exe does not like being in a path with spaces and does not like the codec set as "MP3" but "mp3" works.

audible quickstart still does not present a file in the appdata directory. It seems like everything works. I get through all the questions and get a captcha image. Then cmd window closes.

**Comment by VarSell** [comment]
Unsure of why the **\AppData\Local\Audible\config.toml** file is not getting created after following those steps with **audible quickstart**, try raising an issue [here](https://github.com/mkb79/audible-cli/issues).

Thanks for pointing out the issue with the uppercase and PATH with spaces, will fix them in the next update. 👍
