### ISSUE TITLE
iAmDeaf  need update ?

### ISSUE THREAD

**Issue by writetome1** [VarSell/iAmDeaf#3]
iAmDeaf version use aaxc  file  and
.voucher file: “/data/data/com.audible.application/files/vouchers/”
.database file: “/data/data/com.audible.application/databases/” map_data_storage_v2.db

I'm on android no root Audible it market app
aaxc is there but, as I can see, vouchers and db file are missed
I'm not sure (  as I said I'm on android no root) I'm right ?
I just see a file .companion ! New audible version ?

**Comment by VarSell** [comment]
.voucher file from the android app is different. 
This works with [Audible-cli](https://github.com/mkb79/audible-cli/releases/tag/v0.2.4)  to get the voucher and download the file.
If you want to decrypt aaxc with this, setup your audible profile and download via `iAmDeaf -c <ASIN>`
